<a href="https://colab.research.google.com/github/PocachipMind/MS-AI-School/blob/main/Python/Python_4%3ANumpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.array([1,2,3,4,])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# 으로 초기화된 배열

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 빈 값으로 만들어진 배열

arr = np.empty((4,4))
print(arr)
# 사용했었던 찌꺼기(쓰레기값) 이 나옴.

[[2.35738719e-316 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59031995e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]


In [7]:
# 1로 가득찬 배열을 만든다

arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 배열의 생성

arr = np.arange(10)
print(arr)
# 결과물은 넘파이 배열이다.

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr.shape # 모양

(2, 3)

In [11]:
arr.ndim # 차원

2

In [13]:
arr.dtype # 데이터 타입

dtype('int64')

In [14]:
# 데이터 타입 변경
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [16]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [18]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [19]:
# ndarray 배열의 연산

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [20]:
arr1 + arr2 # 같은 차원 애들끼리 덧셈

array([[ 6,  8],
       [10, 12]])

In [22]:
np.add(arr1, arr2) # 명령어를 사용하여 더하기

array([[ 6,  8],
       [10, 12]])

In [23]:
arr1 * arr2 # 곱셈도 동일

array([[ 5, 12],
       [21, 32]])

In [25]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [29]:
# ndarray 배열 슬라이싱 하기

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
arr.ndim

2

In [28]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [30]:
arr[0,2]

3

In [32]:
arr[0,1:-1]

array([2])

In [34]:
arr[[0,1,2],[2,0,1]] # 첫번째 큰 배열, 두번째 요소

array([3, 4, 8])

In [35]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [37]:
print(arr[idx])

[4 5 6 7 8 9]


csv가 가장 데이터 전달에 용량이 적음. c 콤마로 구분되는 데이터. csv읽기

In [39]:
redwine = np.loadtxt(fname = 'winequality-red.csv',delimiter = ';' , skiprows=1)  # delimiter 뜻 : ;이 구별자로 쓰였다. skiprows = 1 1칸 건너뛰기
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [41]:
# 합계

print(redwine.sum())

152084.78194


In [43]:
# 평균

print(redwine.mean())

7.926036165311652


In [45]:
# 축(axis)

print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [46]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [50]:
print(redwine[:,0])
print(redwine[:,0].mean())

[7.4 7.8 7.8 ... 6.3 5.9 6. ]
8.31963727329581


In [52]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [53]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])